### PR TITLE
Stable identifier message - NOT FOR MERGING - informational only

### PR DESCRIPTION
**Pull request by UnitasBrooks**
I'm a bit confused why I'm getting: 
Error:(326, 54) stable identifier required, but Faker.this.beer() found.
  def beer(seed: Seed): String = Arbitrary.arbitrary[beer.Beer].one(seed).value

Any tips?

### CODE REVIEW

**Comment by etspaceman** [comment]
Heh. Its because the package name of the object (beer) and the function (beer) are the same. I think scala is getting confused with that. 

Perhaps we could use `beerName()`?

**Comment by etspaceman** [comment]
Also, in the future, if you intend for this to not be merged, you can use the "Draft" PR option from GitHub:

https://github.blog/2019-02-14-introducing-draft-pull-requests/

**Comment by UnitasBrooks** [comment]
Ah thank you. Didn't know about the draft PR!

**Comment by etspaceman** [comment]
Neat eh? I only recently learned about it too!

**Comment by etspaceman** [comment]
Closing as this seems resolved. Feel free to open a new one if you have a contribution ready!

**Pull request closed without merging**
